dtpmap/urls.py
from django.contrib import admin
from django.contrib.sitemaps import views as sitemapviews
from django.urls import include, path, re_path
from django.views.decorators.cache import cache_page

from dtpmapapp import views
from dtpmapapp.sitemaps import MVCSitemap, RegionSitemap

sitemaps = {"mvcs": MVCSitemap(), "regions": RegionSitemap()}

# old_api_patterns = [
#     re_path(
#         r"^regions/(?P<region_alias>[-_\w]+)/mvcs/$",
#         views.mvcs_by_region,
#         name="mvc by region",
#     ),
#     re_path(
#         r"^regions/(?P<region_alias>[-_\w]+)/areas/(?P<area_alias>[-_\w]+)/mvcs/$",
#         views.mvcs_by_area,
#         name="mvc by area",
#     ),
#     path("dicts/", views.dicts, name="dictionaries"),
#     path("participant_types/", views.participant_types, name="participant_types"),
#     path("search_region/", views.search_region, name="search region"),
# ]

urlpatterns = [
    path("sitemap.xml", sitemapviews.index, {"sitemaps": sitemaps}),
    re_path(
        r"^sitemap-(?P<section>.+)\.xml$",
        cache_page(24 * 60 * 60)(sitemapviews.sitemap),
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("admin1/", admin.site.urls),
    path("about/", views.about, name="about"),
    path("api/v1/", include(("api.v1.urls", "api_v1"))),
    # path("api/", include((old_api_patterns, "old_api_patterns"))),
    path("", views.home, name="home"),
    re_path(r"^(?P<region_alias>[-_\w]+)/$", views.region, name="region page"),
    re_path(r"^dtp/(?P<mvc_alias>[-_\w]+)/$", views.mvc, name="mvc page"),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns += staticfiles_urlpatterns()

dtpmapapp/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.contrib.gis.db.models import PointField

class Region(models.Model):
    name = models.CharField(max_length=1000, help_text="Region name", null=True, blank=True, default=None, db_index=True)
    alias= models.CharField(max_length=1000, help_text="Region alias", null=True, blank=True, default=None, db_index=True)
    oktmo_code = models.CharField(max_length=20, help_text="Region oktmo code", null=True, blank=True, default=None, db_index=True)
    level = models.IntegerField(help_text="Region level", null=True, blank=True, default=None, db_index=True)
    parent_region = models.ForeignKey('self', help_text="Parent region", null=True, blank=True, default=None, on_delete=models.SET_NULL, db_index=True)
    status = models.NullBooleanField(help_text="Region visible", null=True, blank=True, default=None, db_index=True)
    longitude = models.FloatField(help_text="Region longitude", null=True, blank=True, default=None)
    latitude = models.FloatField(help_text="Region longitude", null=True, blank=True, default=None)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        if self.parent_region:
            return '/' + self.parent_region.alias + '_' + self.alias + '/'
        else:
            return '/' + self.alias + '/'


class Street(models.Model):
    name = models.CharField(max_length=1000, help_text="Street name", null=True, blank=True, default=None, db_index=True)


class Car(models.Model):
    brand = models.CharField(max_length=1000, help_text="Car brand", null=True, blank=True, default=None, db_index=True)
    car_model = models.CharField(max_length=1000, help_text="Car model", null=True, blank=True, default=None, db_index=True)
    color = models.CharField(max_length=1000, help_text="Car color", null=True, blank=True, default=None, db_index=True)
    manufacture_year = models.IntegerField(help_text="Car manufacture year", null=True, blank=True, default=None, db_index=True)

    def __str__(self):
        return self.brand + " " + self.car_model


class Offence(models.Model):
    name = models.CharField(max_length=1000, help_text="Participant offences", null=True, blank=True, default=None, db_index=True)

    def __str__(self):
        return self.name


class MVCType(models.Model):
    name = models.CharField(max_length=1000, help_text="MVC Type name", null=True, blank=True, default=None, db_index=True)
    alias = models.CharField(max_length=1000, help_text="MVC Type alias", null=True, blank=True, default=None, db_index=True)

    def __str__(self):
        return self.name


class MVCParticipantType(models.Model):
    name = models.CharField(max_length=1000, help_text="MVC Type name", null=True, blank=True, default=None, db_index=True)
    label = models.CharField(max_length=1000, help_text="MVC Type label", null=True, blank=True, default=None, db_index=True)
    value = models.BooleanField(max_length=1000, help_text="Is MVC Type Value at first", null=False, blank=False, default=True, db_index=True)

    def __str__(self):
        return self.name


class Nearby(models.Model):
    name = models.CharField(max_length=1000, help_text="Nearby object name", null=True, blank=True, default=None, db_index=True)

    def __str__(self):
        return self.name


class MVC(models.Model):
    region = models.ForeignKey(Region, help_text="MVC region", null=True, blank=True, default=None, on_delete=models.SET_NULL, db_index=True)
    alias = models.CharField(max_length=1000, help_text="MVC alias", null=True, blank=True, default=None, db_index=True)
    datetime = models.DateTimeField(default=None, help_text="MVC date", null=True, blank=True, db_index=True)
    address = models.CharField(max_length=1000, help_text="MVC address", null=True, blank=True, default=None, db_index=True)
    street = models.ForeignKey(Street, help_text="MVC Street", null=True, blank=True, default=None, on_delete=models.SET_NULL, db_index=True)
    type = models.ForeignKey(MVCType, help_text="MVC Type", null=True, blank=True, default=None, on_delete=models.SET_NULL, db_index=True)
    participant_type = models.ForeignKey(MVCParticipantType, help_text="MVC Participant Type", null=True, blank=True, default=None, on_delete=models.SET_NULL, db_index=True)
    longitude = models.FloatField(help_text="MVC longitude", null=True, blank=True, default=None)
    latitude = models.FloatField(help_text="MVC longitude", null=True, blank=True, default=None)
    conditions = JSONField(help_text="MVC conditions", null=True, blank=True, default=None)
    dead = models.IntegerField(help_text="MVC dead count", null=True, blank=True, default=None, db_index=True)
    injured = models.IntegerField(help_text="MVC injured count", null=True, blank=True, default=None, db_index=True)
    participants = models.IntegerField(help_text="MVC participants count", null=True, blank=True, default=None, db_index=True)
    scheme = models.CharField(max_length=100, help_text="MVC scheme number", null=True, blank=True, default=None, db_index=True)
    nearby = models.ManyToManyField(Nearby, help_text="Nearby objects", db_index=True)
    geo_updated = models.BooleanField(help_text="Geo updated", default=None, null=True)
    created_at = models.DateTimeField(auto_now=True)
    point = PointField(help_text="MVC point", default=None, null=True)
    point_source = PointField(help_text="MVC source point", default=None, null=True)

    def __str__(self):
        return self.type.name + " " + self.region.name + " " + str(self.datetime)

    def get_absolute_url(self):
        return '/dtp/' + self.alias + '/'


class SourceData(models.Model):
    data = JSONField(help_text="Source data", default=dict)
    date = models.DateTimeField(auto_now=True)
    mvc = models.ForeignKey(MVC, help_text="Source data mvc", on_delete=models.CASCADE)


class Participant(models.Model):
    role = models.CharField(max_length=1000, help_text="Participant role", null=True, blank=True, default=None, db_index=True)
    offences = models.ManyToManyField(Offence, help_text="Participant offences", db_index=True)
    driving_experience = models.IntegerField(help_text="Participant driving experience (years)", null=True, blank=True)
    status = models.CharField(max_length=1000, help_text="Participant status", null=True, blank=True, default=None)
    gender = models.CharField(max_length=1000, help_text="Participant gender", null=True, blank=True, default=None)
    abscond = models.CharField(max_length=1000, help_text="Participant abscond", null=True, blank=True, default=None)
    mvc = models.ForeignKey(MVC, help_text="MVC", null=True, blank=True, default=None, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, help_text="Car", null=True, blank=True, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.role + " " + self.gender + self.mvc.region.name

templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load humanize %}

{% block page-styles %}
    <link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <div class="container text">
        <p>Проект "Карта ДТП" посвящен проблеме дорожно-транспортных происшествий в России. К сожалению, качество
            дорожной инфраструктуры и городской среды приводит к большому количеству жертв – в 2017 году на дорогах
            страны погибло 19088 человек.</p>
        <p>Цель проекта - повышение безопасности дорожного движения и снижение смертности в ДТП. "Карта ДТП" не только
            собирает данные о ДТП, но и помогает экспертам, активистам, журналистам и прочим неравнодушным анализировать
            их. Всё это может способствовать выявлению реальных причин ДТП, оценке инфраструктуры, а также выработке
            более качественных программ по повышению безопасности на дорогах.</p>
        <P>Мы используем данные с официального портала <a href="http://stat.gibdd.ru" target="_blank">статистики
            ГИБДД</a>. Из-за ошибок в исходных данных наш сервис также может содержать неточности.</P>
        <br>
        <h4>
            Добавление собственных маркеров на карту
        </h4>
        <p>Вы можете добавлять собственные маркеры на карту, чтобы проводить исследования по сторонним объектам - школам, переходам и т.д. Для этого на панели фильтров внизу ест ькнопка, куда необходимо загрузить файл в формет json.</p>
        <p>Формат:</p>
        <figure class="highlight">
            <pre><code>
[
  {
    "name": "Школа",
    "longitude": 37.625385,
    "latitude": 55.751352
  },
  ...
]
        </code></pre>
        </figure>
        <br><br>
        <h4>Контакты</h4>
        <div class="row">
            <div class="col-6">
                <img src="{% static "media/ustnv.jpg" %}"
                     style="max-width: 80%;margin: 20px" class="rounded-circle">
                <b>Сергей Устинов</b>
                <p style="margin: 0">Отвечает за технические вопросы</p>
                <a href="https://www.facebook.com/ustnv.s">https://www.facebook.com/ustnv.s</a>
            </div>
            <div class="col-6">
                <img src="{% static "media/rad.jpg" %}"
                     style="max-width: 80%;margin: 20px" class="rounded-circle">
                <b>Алексей Радченко</b>
                <p style="margin: 0">Отвечает за развитие</p>
                <a href="https://www.facebook.com/alexradchenko">https://www.facebook.com/alexradchenko</a>
            </div>
        </div>
        <br><br>
        <h4 id="media">СМИ о нас</h4>
        <ul>
            <li><a href="https://daily.afisha.ru/news/18145-aktivisty-sozdali-kartu-vseh-dtp-v-moskve/"><b>Афиша</b> - Активисты создали карту всех ДТП в Москве</a></li>
            <li><a href="https://www.the-village.ru/village/city/news-city/317621-karta-dtp"><b>The Village</b>  - Интерактивная статистика ДТП на улицах Москвы</a></li>
            <li><a href="https://360tv.ru/news/obschestvo/sozdana-onlajnkarta-dtp-moskvy/"><b>Телеканал 360</b>  - оздана онлайн‐карта ДТП Москвы</a></li>
            <li><a href="https://tjournal.ru/73169-moskovskie-aktivisty-zapustili-onlayn-kartu-vseh-dtp-v-gorode"><b>Tjournal</b>  - Московские активисты запустили онлайн-карту всех ДТП в городе</a></li>
            <li><a href="https://www.msk.kp.ru/daily/26851/3893361/"><b>Комсомольская правда</b> - В Москве опубликовали карту ДТП за последние три года</a></li>
            <li><a href="https://rg.ru/2018/07/04/reg-cfo/v-moskve-razrabotali-narodnuiu-kartu-dtp.html"><b>Российская газета</b> - В Москве разработали народную карту ДТП</a></li>
        </ul>

    </div>


{% endblock %}

{% block page-scripts %}
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>

    <script>
        (function () {
            function makeSearch(term, callback) {
                $.get('/api/search_region/?term=' + term).done(function (data) {
                    options = data.regions.map(function (region) {
                        return {
                            label: region.name,
                            value: region.name,
                            actualValue: region.alias
                        }
                    })
                    callback(options);
                });
            }

            function goToRegionPage(regionAlias) {
                var url = '/' + regionAlias + '/';
                window.location.href = url;
            }

            $('#regionSearch').autocomplete({
                minLength: 2,
                source: function (request, response) {
                    makeSearch(request.term, response);
                },
                select: function (event, ui) {
                    goToRegionPage(ui.item.actualValue);
                }
            });
        })();
    </script>
{% endblock %}

templates/area.html
<!doctype html>

{% load static %}
{% load md5url %}
{% load render_bundle from webpack_loader %}

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% include "head.html" %}

        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
              integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
              crossorigin=""/>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,900&amp;subset=cyrillic,cyrillic-ext" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
        <link rel="stylesheet" href="https://unpkg.com/react-select@1.2.1/dist/react-select.css">
        <link rel="stylesheet" href="{% md5url 'css/dtp-map.css' %}">
        <script src='https://api.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.js'></script>
        <link href='https://api.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.css' rel='stylesheet' />
    </head>
    <body>
        <div class="dtp-app-container d-flex flex-column">
            {% include "navigation.html" %}

            <div id="react-app" class="flex-grow-1 d-flex flex-column"></div>
        </div>

        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
                integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
                crossorigin="anonymous"></script>

        <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>


        {% render_bundle 'main' %}
        <script>
            window.initApp({
                regionAlias: '{{ region_alias }}',
                cityName: '{{ region.name }}',
                areaAlias: {{ area_alias | safe }},
                regionLat: {{ region.latitude | escapejs }},
                regionLon: {{ region.longitude | escapejs  }},
                regionLevel: {{ region.level }},
            });
        </script>

    </body>
</html>

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
<head>
<meta name="google-site-verification" content="06wnJrpzVrL1VyNldXxXHuxeks1dVIqur-Qmg2-X3xU" />

    {% include "head.html" %}

    {% block page-styles %}
    {% endblock %}



</head>
<body>
{% include "navigation.html" %}

{% block content %}
{% endblock %}

{% include "footer.html" %}

{% block scripts %}
    <script>
        if ($(document).height() <= $(window).height())
            $("footer").addClass("fixed-bottom");
    </script>
{% endblock %}

{% block page-scripts %}
{% endblock %}

</body>
</html>

templates/footer.html
{% load staticfiles %}

<footer>
    <div class="container">
    <div class="row">
        <div class="col-md-6 license text-left" style="">
            <div style="max-width: 500px;margin: 0 auto;">
            <div style="float: left;margin: 10px 30px 10px 10px">
                <a href="http://creativecommons.org/licenses/by/4.0/" target="_blank">
                <img src="{% static "media/creative-commons-1.png" %}">
            <img src="{% static "media/creative-commons-2.png" %}">
                    </a>
            </div>

                <p>Использование материалов возможно с указанием активной ссылки на сайт. Источник данных - <a href="http://stat.gibdd.ru" target="_blank">ГИБДД</a>.</p>
                </div>
        </div>
        <div class="col-md-6 text-center footer-menu" style="">
            <a href="/">Главная</a>
            <a href="/about/">О проекте</a>
            <a href="mailto:info@dtp-stat.ru">info@dtp-stat.ru</a>

        </div>
    </div>
    </div>
</footer>

templates/mvc.html
{% extends "base.html" %}

{% load staticfiles %}
{% load humanize %}

{% block content %}
    <div class="container mvc">
        <div class="row">
            <div class="col-md-6">
                <p>{{ mvc.datetime|date:"H:i | d.m.Y, l" }} </p>
                <h2>{{ mvc.type.name }}</h2>

                {% for participant in mvc.participant_set.all|dictsort:"status" %}
                    <i class="fa fa-male" aria-hidden="true" style="color:{% if "аненый" in participant.status %}#ffc107{% elif "кончал" in participant.status %}#dc3545{% else %}#6c757d{% endif %};font-size: 30px" title="{{ participant.status }}" data-toggle="tooltip" data-placement="bottom"></i>
                {% endfor %}
                <h5>Нарушения</h5>
                {% for offence in offences %}
                    <p><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ offence.role }} – {{ offence.offences__name }}</p>
                {% endfor %}
                <h5>Обстановка</h5>
                <div class="condition">
                    <div class="condition-name">
                        <p>Условия</p>
                    </div>
                    <div class="condition-list">
                        {% for object in mvc.conditions %}
                            <p>{{ object }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class="condition">
                    <div class="condition-name">
                        <p>Поблизости</p>
                    </div>
                    <div class="condition-list">
                        {% for object in mvc.nearby.all %}
                            <p>{{ object.name }}</p>
                        {% endfor %}
                    </div>
                </div>
                <h5>Участники</h5>
                <div class="participants">
                    {% for car in cars %}
                        <div class="car-participant">
                            <div class="car">
                                <p>{{ car.brand }}{% if car.car_model %} ({{ car.car_model }}){% endif %}, {{ car.manufacture_year }}</p>
                            </div>
                            <div class="persons">
                                {% for participant in car.participant_set.all|dictsort:"role" %}
                                <p>
                                    <i class="fa fa-male" aria-hidden="true" style="color:{% if "аненый" in participant.status %}#ffc107{% elif "кончал" in participant.status %}#dc3545{% else %}#6c757d{% endif %}" title="{{ participant.status }}" data-toggle="tooltip" data-placement="right"></i>
                                    {{ participant.role }}{% if participant.gender %},
                                    {{ participant.gender }}{% endif %}{% if participant.driving_experience %}, стаж (лет) - {{ participant.driving_experience }}{% endif %}
                                </p>
                                {% for offence in participant.offences.all %}
                                    <p class="offence"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ offence.name }}</p>
                                {% endfor %}
                            {% endfor %}
                            </div>

                        </div>
                    {% endfor %}

                    {% for participant in participants %}
                        <div class="car-participant">
                            <div class="car"></div>
                            <div class="persons">
                                <p><i class="fa fa-male" aria-hidden="true" style="color:{% if "аненый" in participant.status %}#ffc107{% elif "кончал" in participant.status %}#dc3545{% else %}#6c757d{% endif %}" title="{{ participant.status }}" data-toggle="tooltip" data-placement="right"></i>
                            {{ participant.role }}, {{ participant.gender }}</p>

                        {% for offence in participant.offences.all %}
                            <p class="offence"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> {{ offence.name }}</p>
                        {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="address">
                    <div class="row">
                        <div class="col-md-12">
                            <p>{% if mvc.address %}{{ mvc.address }}{% else %}{{ mvc.latitude }} {{ mvc.longitude }}{% endif %}</p>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            {% if mvc.scheme %}
                                <img src="http://stat.gibdd.ru/img/SDTP/{{ mvc.scheme }}.png" class="scheme" style="">
                            {% endif %}
                            <div id="mapid" class="map"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div id="player2" class="panorama"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
    <hr>
    <div class="container text-center partner">
    <h5>Ежегодно на дорогах России погибает 20000 человек. Мы создаем сервис, который делает дороги безопаснее. Если вы разделяете наши ценности, то поддержите нас.</h5>
        <a href="/#partner" class="btn btn-info" role="button">Поддержать</a>
    </div>


{% endblock %}

{% block scripts %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
          integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
          crossorigin=""/>

    <script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
    });
    </script>
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
            integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
            crossorigin=""></script>
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;load=package.full"></script>
    <script>
        var mymap = L.map('mapid', {zoomControl: false}).setView([{{ mvc.latitude|safe }}, {{ mvc.longitude|safe }}], 15);
        var marker = L.marker([{{ mvc.latitude|safe }}, {{ mvc.longitude|safe }}]).addTo(mymap);
        L.tileLayer('https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png', {
            maxZoom: 18,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="http://cartodb.com/attributions">CartoDB</a>',
            id: 'mapbox.streets'
        }).addTo(mymap);
    </script>
    <script>
        ymaps.ready(function () {
            // Для начала проверим, поддерживает ли плеер браузер пользователя.
            if (!ymaps.panorama.isSupported()) {
                // Если нет, то просто ничего не будем делать.
                return;
            }

            // Для добавления панорамы на страницу также можно воспользоваться
            // методом panorama.createPlayer. Этот метод ищет ближайщую панораму и
            // в случае успеха создает плеер с найденной панорамой.
            ymaps.panorama.createPlayer(
                    'player2',
                    [{{ mvc.latitude|safe }}, {{ mvc.longitude|safe }}],
                    { controls: ['panoramaName'] }
            )
                    .done(function (player) {
                        // player – это ссылка на экземпляр плеера.
                    });
        });


    </script>
{% endblock %}

templates/navigation.html
{% load staticfiles %}

<nav class="navbar topbar navbar-expand">
    <div class="container">
        <a class="navbar-brand" href="/"><img src="{% static 'media/logo.png' %}"
                                              style="width: 50px;height: auto;margin-right: 10px"> Карта ДТП</a>

        <ul class="nav navbar-nav ml-auto">
            <h3>
                {% if region %}
                    {{ region }}
                    {% if region.parent_region %}
                        | {{ region.parent_region }}
                    {% endif %}
                {% else %}
                    <a href="https://twitter.com/dtp_stat"><i class="fa fa-twitter-square" aria-hidden="true"></i> dtp_stat</a>
                {% endif %}
            </h3>
        </ul>

    </div>
</nav>

templates/no_area.html
{% extends "base.html" %}

{% load staticfiles %}
{% load humanize %}

{% block page-styles %}
    <link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet" type="text/css">
    <meta property="og:title" content="Карта ДТП - {{ region_item }}"/>
    <title>Карта ДТП - {{ region_item }}</title>

{% endblock %}

{% block content %}
    <div class="container no-area">
        <h2 class="text-center">Привет! Твой регион пока не добавлен на карту.</h2><br>


    </div>
{% endblock %}

templates/region.html
{% extends "base.html" %}

{% load staticfiles %}
{% load humanize %}

{% block content %}
    <div class="container ">
        <h1>{{ region.name }}</h1>
        {% for children_region in children_regions %}
            <p><a href="/{{ region.alias }}/{{ children_region.alias }}/">{{ children_region }}</a></p>
        {% endfor %}
        <hr>
        {% for mvc in mvc_list %}
            <p><a href="{{ mvc.alias }}">{{ mvc }}</a></p>
        {% endfor %}
    </div>


{% endblock %}